#spring.application.name=hello-spring
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      # 자동으로 테이블을 만들어주는 기능을 끔
      ddl-auto: none